### ISSUE TITLE
Wishlist search function disappears when 'back to search' is clicked on

### ISSUE THREAD

**Issue by lagunasmel** [flummoxing/BookSwap#134]
After conducting a search on the Wishlist page, the ability to search disappears if 'back to search' is clicked on. 

Steps to mimic this bug:
1. Conduct a search on the 'My Wishlist' page, i.e. 'Harry Potter' 
2. Scroll down after search results are displayed, and select 'back to search' 
3. The HTML element inputs to conduct the search disappear along with the 'add to wishlist' header

Button to click on:
<img width="879" alt="Screen Shot 2020-11-27 at 3 53 38 PM" src="https://user-images.githubusercontent.com/30912739/100484625-31630780-30cb-11eb-82dc-62a1e26d7354.png">

Result after clicking:
<img width="1273" alt="Screen Shot 2020-11-27 at 3 53 55 PM" src="https://user-images.githubusercontent.com/30912739/100484634-3aec6f80-30cb-11eb-9752-4eca5d87c8f7.png">

**Comment by BenWichser** [comment]
Fixed via one line of javascript.

Within `static/js/my-wishlist.js`, the function `cancelAddBook()` needed to show one hidden \<div\>.
```javascript
function cancelAddBook() {
    $("#confirmBook").hide();
    $("#searchResults").hide();
    $("#listBook").show();
    $('#wishlistSearch').show();
}
```

The final line, `$('#wishlistSearch').show();`, was missing.
